# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 51e2d4aca87922599a684f8ec8d6c626feced9d69101a2c4aa96c151e92787e618a9301e4a63990740ffa0a20c0b8769a4af923a5ecedc58ee49c51f3e71729c

test:
  secret_key_base: c59cf252be1edc4120d8db2aa6059e2efaa420adf8fec109730804cb04eb8c7f085f179d50e200f29baf3280a2efa47d4adeb06f7af291b2310a7adfe8400fa0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
